// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: stanza/hub/v1/auth.proto

package hubv1connect

import (
	context "context"
	errors "errors"
	v1 "github.com/StanzaSystems/sdk-go/gen/go/stanza/hub/v1"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "stanza.hub.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceGetBearerTokenProcedure is the fully-qualified name of the AuthService's
	// GetBearerToken RPC.
	AuthServiceGetBearerTokenProcedure = "/stanza.hub.v1.AuthService/GetBearerToken"
)

// AuthServiceClient is a client for the stanza.hub.v1.AuthService service.
type AuthServiceClient interface {
	GetBearerToken(context.Context, *connect_go.Request[v1.GetBearerTokenRequest]) (*connect_go.Response[v1.GetBearerTokenResponse], error)
}

// NewAuthServiceClient constructs a client for the stanza.hub.v1.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authServiceClient{
		getBearerToken: connect_go.NewClient[v1.GetBearerTokenRequest, v1.GetBearerTokenResponse](
			httpClient,
			baseURL+AuthServiceGetBearerTokenProcedure,
			opts...,
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	getBearerToken *connect_go.Client[v1.GetBearerTokenRequest, v1.GetBearerTokenResponse]
}

// GetBearerToken calls stanza.hub.v1.AuthService.GetBearerToken.
func (c *authServiceClient) GetBearerToken(ctx context.Context, req *connect_go.Request[v1.GetBearerTokenRequest]) (*connect_go.Response[v1.GetBearerTokenResponse], error) {
	return c.getBearerToken.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the stanza.hub.v1.AuthService service.
type AuthServiceHandler interface {
	GetBearerToken(context.Context, *connect_go.Request[v1.GetBearerTokenRequest]) (*connect_go.Response[v1.GetBearerTokenResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(AuthServiceGetBearerTokenProcedure, connect_go.NewUnaryHandler(
		AuthServiceGetBearerTokenProcedure,
		svc.GetBearerToken,
		opts...,
	))
	return "/stanza.hub.v1.AuthService/", mux
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) GetBearerToken(context.Context, *connect_go.Request[v1.GetBearerTokenRequest]) (*connect_go.Response[v1.GetBearerTokenResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("stanza.hub.v1.AuthService.GetBearerToken is not implemented"))
}
