name: Trigger Builds in Downstream Repos
on:
  push:
    branches: [ "main" ]
  
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: StanzaSystems/fiberstanza-test-app
          event-type: sdk-push
